# SPDX-FileCopyrightText: 2023 - 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
# If docker userns is activated, the files that are mounted in the container must have a different uid and gid on the Docker host.
- name: Determine uid and gid for the directories which are mounted in the container
  ansible.builtin.set_fact:
    valkey_host_filesystem_uid: "{{ valkey_uid if not valkey_docker_userns_enabled else (valkey_uid | int + valkey_docker_userns_offset) | string }}"
    valkey_host_filesystem_gid: "{{ valkey_gid if not valkey_docker_userns_enabled else (valkey_gid | int + valkey_docker_userns_offset) | string }}"
  when: valkey_enabled | bool
  tags:
    - always
    
- name: Perform Valkey installation tasks
  when: valkey_enabled | bool
  tags:
    - setup-all
    - setup-valkey
    - install-all
    - install-valkey
  block:
    - name: Validate Valkey configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Valkey
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Valkey uninstallation tasks
  when: not valkey_enabled | bool
  tags:
    - setup-all
    - setup-valkey
  block:
    - name: Uninstall Valkey
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
